clash_fobNames =
[
	"FOB SmanPost",
	"FOB Matt Damon",
	"FOB Benis",
	"FOB Bepis",
	"FOB Schnitzel",
	"FOB Sweetchild",
	"FOB Whale's Shitty GIF",
	"FOB Blob",
	"FOBbity",
	"FOB Harambe",
	"Test FOB Please Ignore",
	"FOB Saget",
	"FOB Warrior Mindset",
	"FOB Shiboleet",
	"FOB Hard Charger",
	"FOB Your Mom's House",
	"FOB Hustler",
	"FOB !rambo",
	"FOB the Builder",
	"Filly FOB Thornton",
	"The FOBbit: An Unexpected Journey",
	"Mein FOB",
	"FOB'et About It",
	"The FOBbit: The Desolation of Tanaka",
	"FOB Brooks",
	"FOB FOB",
	"FOB Enemy Infantry",
	"FOB Sheepdogs",
	"FOB I Can't Believe It's Not COP",
	"FOB Deez Nutz",
	"FOB Something About Asians",
	"Coalition Party FOB",
	"Cowboy BeFOB",
	"FOB Better or FOB Worse",
	"FOB It Like It's Hot",
	"Right FOB and Wrong FOB",
	"FOBzilla",
	"FOBbies",
	"Get a FOBby",
	"Damn It FOBby",
	"FOB Dylan",
	"FOB Dyslexi (sp?)",
	"FOB Comms Were Good",
	"FOB BOF (Again)",
	"I Can't Believe It's Not FOB",
	"FOOOOOOOOOOOOOOOOOOB",
	"FOB Mike Doesn't Like Pings",
	"FOB McFOBFace",
	"Go FOB Yourself",
	"FOB for Hard Chargers Only",
	"FOBba Fett",
	"FOBbington FOB FOBson III Esq. Ph.D",
	"FOB New DnD NPC?",
	"To FOB Or Not To FOB",
	"FOB Twice A Week At The Fuckin' Least!",
	"FOB Is On Me :(",
	"FOB BTR - No, Idiot, It's a BRDM",
	"FOB Squeak",
	"FOB Off",
	"FOB, 100m, Front",
	"Slob On My FOB",
	"FOB On The COB",
	"FOB BMP - No, Idiot, It's a BTR",
	"FOB All Over Me",
	"FOB POG",
	"FOB rm -rf /",
	"FOBbed Myself",
	"FOB Ratio+L",
	"FOB Maidenless",
	"FOB No Bitches",
	"FOB Girls Only",
	"FOB ASL Died Again",
	"FOB My Mom Thinks I'm Handsome",
	"FOB No, It's a PKM",
	"FOB BDSM I Mean BRDM",
	"FOB They/Them",
	"Nice FOB Retard",
	"FOB Xi/Xiao",
	"FOB Without the Bullshit",
	"Panic! At the FOB",
	"FOB Brownsville",
	"FOB Lazz's Shitty CopyPasta",
	"FOB Dole",
	"FOB On My Nob",
	"Keep My Wife's FOB Out of Your Fuckin' Mouth!",
	"Oh My God! I'm Gonna FOB!",
	"FOB @company",
	"FOB Dante and FOB Hawk",
	"FOBbert Downey Jr.",
	"FOB Beeper",
	"FOB Scoop",
	"No Country For Old FOBs",
	"FOB Nothing Here, Promise",
	"FOBbert Dinero",
	"FOB Marley",
	"FOB Greg's Crash Site",
	"FOB Convoy Mission",
	"FOB Zombie",
	"FOBbit Hole",
	"FOB Choccomommy",
	"FOB Detroit",
	"Steve FOBs",
	"FOB and Weave",
	"FOBbly Wobbly",
	"Jay and Silent FOB",
	"FOB Lowe",
	"The FOB",
	"The Glitch FOB",
	"FOB While {True} do {publicVariable 'FOB'}",
	"Dude, Where's My FOB",
	"The FOB Next Door",
	"Enemy FOB",
	"Enemy At the FOBs",
	"Saving Private FOB",
	"Jay and Silent FOB Strike Back",
	"Jay and Silent FOB Get a Reboot",
	"THe FOB and the Furious",
	"Phineas and FOB",
	"Starship FOBbers",
	"FOB Supa Hot Fiya!!!",
	"404 FOB Not Found",
	"How I Learned to Stop Worrying and Love the FOB",
	"Ace Ventura: FOB Detective",
	"What if FOB Was One of Us",
	"The Good, the Bad, and the FOB",
	"A Fist Full of FOBS",
	"A FOB Full of Bullets",
	"Who Let the FOBs Out",
	"FOB'n Off",
	"The Return of the FOB",
	"The Texas Chain FOB Massacre",
	"You Can't Handle the FOB",
	"Look Who's FOB'n",
	"Rebel Without a FOB",
	"Harry FOBber",
	"A Series of Unfortunate FOBs",
	"Big Trouble in Little FOBs",
	"FOB v Ferrari",
	"Monty Python & The Holy FOB",
	"The FOB Lebowski",
	"FOB Billy Herrington",
	"Go Ahead and Make My FOB",
	"2001: A Space FOByssey",
	"We're Gonna Need a Bigger FOB",
	"FOBs. Lots of FOBs.",
	"Sir, Finishing This FOB",
	"Team FOBtress 2",
	"FOB, James FOB",
	"FOBs and Recreation",
	"Build it and They Will FOB",
	"FOBin Williams",
	"FOBChamp",
	"Notorious FOB",
	"Where is the FOB",
	"Not a FOB",
	"Ain't Got No FOB in It",
	"Cops and FOBbers",
	"Lord of the FOBs",
	"Where's the FOB?",
	"FOB [Insert Name Here]",
	"FOB Sponsored by Raid: Shadow Legends",
	"FOB Sponsored by Carl's Jr.",
	"The FOB Formerly Known as Prince",
	"The Little FOB That Could",
	"FOB, 200m, Front!",
	"Snoop FOB",
	"Guys Only Want One FOB and It's Disgusting",
	"FOB Based of Fire",
	"Dwayne the FOB Johnson",
	"FOB at Home:"
];