clash_fobNames =
[
	" You've Made a Mistake",
	" Uh Oh",
	" SmanPost",
	" Matt Damon",
	" Benis",
	" Bepis",
	" Schnitzel",
	" Sweetchild",
	" Blob",
	"bity",
	" Harambe",
	" Test FOB Please Ignore",
	" Saget",
	" Warrior Mindset",
	" Shibboleet",
	" Hard Charger",
	" for Web Warriors",
	" Your Mom's House",
	" Hustler",
	" !rambo",
	" the Builder",
	" The FOBbit: An Unexpected Journey",
	" Dynamo",
	"'et About It",
	" The FOBbit: The Desolation of Tanaka",
	" Nimrod",
	" Filthy FOB Fornton",
	" Brooks",
	" FOB",
	" Husky",
	" Enemy Infantry",
	" Sheepdogs",
	" I Can't Believe It's Not COP",
	" Deez Nutz",
	" Something About Asians",
	" Cowboy BeFOB",
	" Better or FOB Worse",
	" it Like It's HOT",
	" Ross",
	"zilla",
	" Get a FOBby",
	" Dylan",
	" Dislexi (sp?)",
	" Comms Were Good",
	" Foooooooooooob",
	" Mike Doesn't Like Pings",
	"by McFOBFace",
	" BOB",
	"ba Fett",
	"bington FOB FOBson II Esq. Ph.D",
	" New DnD NPC?",
	" Twice A Week At The Fuckin' Least!",
	" Is On Me",
	" Squeak",
	" Off",
	" Man, 100m, Front!",
	" Our Bussy",
	" on the Cob",
	" No it's Actually a BRDM",
	" All Over Me",
	" Fuck Off Techniker",
	"bed Myself",
	" Ratio+L",
	" Maidenless",
	" No Bitches",
	" ASL Died Again",
	" BOF (Again)",
	" It's Actually a PKM",
	" BDSM I Mean BRDM",
	" They/Them",
	" Good Joke Retard",
	" Arma With the Bullshit",
	" Brownsville",
	" Lazz's Weird CopyPasta",
	" @company",
	" Dole",
	" Bing Bong",
	" On My Nob",
	" Dante",
	" Hawk",
	"bert Downey Jr",
	" Beeper",
	" Scoop",
	"bert",
	"bert DiNero",
	" Remington",
	" Chippendales",
	" Barefax",
	" Grizzly",
	" Silicone",
	" Marley",
	" Greg's Crash Site",
	" Jester's Crash Site",
	" Shima's Powerline",
	" Svir's March To The Sea",
	" Nikrue's Girlfriend",
	" Batcam's Blackbelt",
	" Lazz's Friends",
	" Nikrue's Pegging Den",
	" Svir's Furry Convention",
	" Mike's Tallywacker",
	" Cole's Zombie Friends",
	" Hawk's Keyboard",
	" Tilla Watches Anime",
	" Hawk's Pretend Farm",
	" Lazz's Glass of Chocolate Milk",
	" Svir's Feel-Good Button",
	" Ocean Man's Virginity",
	" Convoy Mission"
];